spring.application.name=cloudspend-api

# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/cloudspend}
spring.datasource.username=${DB_USERNAME:cloudspend}
spring.datasource.password=${DB_PASSWORD:cloudspend_dev}

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# ===============================
# ACTUATOR / MONITORING
# ===============================

management.endpoints.web.exposure.include=health,info